In [2]:
import pandas as pd
data = pd.read_csv("p2c-attempts-v1.csv")
data2 = data.replace('A01', 1).replace('A02', 2).replace('A03', 3)
print(data2.dtypes)

student            int64
assignment         int64
attempt            int64
grade              int64
submission time    int64
dtype: object

In [3]:
#data3 = data2.sort_values("student")
data3 = data2.sort_values(['student', 'assignment', "attempt"])
data3

      student  assignment  attempt  grade  submission time
1082    10133           1        1     85               35
1442    10133           1        2     81               32
385     10133           1        3     81               34
627     10133           1        4     97               35
1923    10133           1        5     88                7
...       ...         ...      ...    ...              ...
342     99140           2        1     85              -97
638     99140           2        2     72              -99
1591    99140           2        3     98              -99
633     99858           1        1     76              -39
2       99858           2        1     18              -40

[1968 rows x 5 columns]

In [7]:
data3.min()

student            10133
assignment             1
attempt                1
grade                  0
submission time      -99
dtype: int64

In [8]:
data3.max()

student            99858
assignment             3
attempt               17
grade                102
submission time      200
dtype: int64

In [4]:
# does procrastinate - 1, does not procrastinate - 0
data3["procrastination"] = data3["submission time"] < 0
data4 = data3.replace(True, 1).replace(False, 0)
print(data4.dtypes)

student            int64
assignment         int64
attempt            int64
grade              int64
submission time    int64
procrastination    int64
dtype: object

In [5]:
data4 = data4.rename(columns={'submission time': 'submission_time'})
data4

      student  assignment  attempt  grade  submission_time  procrastination
1082    10133           1        1     85               35                0
1442    10133           1        2     81               32                0
385     10133           1        3     81               34                0
627     10133           1        4     97               35                0
1923    10133           1        5     88                7                0
...       ...         ...      ...    ...              ...              ...
342     99140           2        1     85              -97                1
638     99140           2        2     72              -99                1
1591    99140           2        3     98              -99                1
633     99858           1        1     76              -39                1
2       99858           2        1     18              -40                1

[1968 rows x 6 columns]

In [6]:
# iterating the columns
for col in data4.columns:
    print(col)

student
assignment
attempt
grade
submission_time
procrastination

In [7]:
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

# Create the features
features = ["assignment", "attempt", "grade", "submission_time"]

# Create the target variable
target = "procrastination"

# Split the data into training and test sets
X_train, X_test, y_train, y_test = train_test_split(data4[features], data4[target], test_size=0.20)

# Create the logistic regression model
model = LogisticRegression()

# Train the model
model.fit(X_train, y_train)

# Evaluate the model
score = model.score(X_test, y_test)
print(score)

1.0