In [1]:
import pandas as pd
data = pd.read_csv("p2c-attempts-v1.csv")
data2 = data.replace('A01', 1).replace('A02', 2).replace('A03', 3)
print(data2.dtypes)

student            int64
assignment         int64
attempt            int64
grade              int64
submission time    int64
dtype: object

In [111]:
#data3 = data2.sort_values("student")
data3 = data2.sort_values(['student', 'assignment', "attempt"])
data3
#data4 = data3[:1966]
#data4

      student  assignment  attempt  grade  submission time
1082    10133           1        1     85               35
1442    10133           1        2     81               32
385     10133           1        3     81               34
627     10133           1        4     97               35
1923    10133           1        5     88                7
...       ...         ...      ...    ...              ...
342     99140           2        1     85              -97
638     99140           2        2     72              -99
1591    99140           2        3     98              -99
633     99858           1        1     76              -39
2       99858           2        1     18              -40

[1968 rows x 5 columns]

In [23]:
df = pd.read_csv("p2c-grades-v1.csv")
df2 = df.sort_values(['student'])
df2

     student  total
225    10133     92
4      10406      5
63     10884     72
185    11102      0
149    11409     74
..       ...    ...
177    96732     86
75     97979     68
40     98255     15
203    99101     73
37     99140     80

[243 rows x 2 columns]

In [138]:
attempts_list = data3["student"].values.tolist()
attempts = [*set(attempts_list)]
print(len(attempts))
print(attempts)

261
[93696, 94213, 84998, 83977, 69644, 61454, 23055, 43025, 68113, 31251, 38932, 67604, 96274, 89623, 99858, 60955, 65564, 41502, 13857, 57380, 44069, 78884, 79398, 45097, 31787, 16940, 47148, 60972, 80429, 93741, 74801, 36914, 96308, 55351, 26168, 50745, 60984, 70201, 19005, 30269, 86077, 43586, 85058, 63045, 53834, 87115, 94289, 14937, 17497, 32348, 18526, 66144, 11873, 15458, 19041, 88677, 66156, 51822, 46193, 23666, 35443, 69749, 19062, 93814, 24697, 53370, 52859, 77946, 57982, 10884, 23172, 19591, 44169, 78476, 89232, 11409, 20627, 31379, 34963, 95382, 26263, 67736, 93852, 66205, 95903, 38048, 60064, 33954, 71843, 80545, 66213, 10406, 88741, 15528, 45225, 29866, 92329, 94372, 74928, 45748, 15541, 54454, 72887, 12472, 44729, 50361, 96443, 39612, 97979, 79038, 12481, 14533, 13512, 54472, 86732, 65229, 33490, 93907, 88788, 29397, 38615, 74969, 50907, 22751, 45285, 29414, 65769, 62702, 78575, 88304, 83185, 91888, 25848, 20216, 34047, 37119, 86274, 17668, 61701, 64773, 26375, 83204, 87304, 30989, 92431, 83216, 25873, 82705, 65303, 69402, 14107, 17692, 35099, 99101, 96543, 18208, 86825, 62250, 42798, 55090, 68402, 44853, 61237, 47931, 24386, 99140, 90439, 82252, 78160, 51025, 31570, 32092, 94559, 77670, 45927, 55143, 63335, 45418, 45420, 47468, 96110, 50543, 26996, 38261, 49013, 80758, 83832, 77180, 82815, 18306, 40835, 30596, 35716, 56194, 45960, 55690, 64395, 79243, 65937, 53650, 60307, 91537, 10133, 19863, 27545, 96665, 15771, 16284, 33179, 78749, 93085, 96155, 19873, 56739, 84900, 36776, 30122, 59819, 17836, 86956, 52655, 34226, 46514, 48562, 54196, 57270, 60343, 77747, 92089, 89018, 17851, 67003, 66495, 16322, 79300, 95172, 19910, 31687, 55243, 98255, 83410, 63445, 28118, 40923, 47580, 96732, 18402, 21476, 39908, 44005, 63974, 35817, 68076, 34285, 43503, 50671, 26099, 20468, 14840, 13819, 33791]

In [137]:
grades_list = df2["student"].values.tolist()
grades = [*set(grades_list)]
print(len(grades))
print(grades)

243
[93696, 94213, 84998, 83977, 69644, 61454, 43025, 96274, 31251, 38932, 67604, 89623, 60955, 65564, 41502, 13857, 78884, 44069, 79398, 45097, 31787, 16940, 47148, 60972, 80429, 93741, 74801, 36914, 96308, 55351, 26168, 60984, 70201, 19005, 30269, 40513, 43586, 85058, 63045, 53834, 87115, 94289, 14937, 17497, 49753, 32348, 18526, 66144, 11873, 15458, 19041, 88677, 66156, 51822, 46193, 23666, 35443, 69749, 19062, 93814, 24697, 53370, 52859, 77946, 57982, 10884, 23172, 19591, 44169, 78476, 89232, 11409, 20627, 31379, 34963, 95382, 26263, 93852, 95903, 38048, 60064, 33954, 71843, 80545, 66213, 10406, 88741, 15528, 45225, 29866, 92329, 94372, 74928, 45748, 15541, 54454, 72887, 12472, 44729, 50361, 96443, 39612, 97979, 79038, 12481, 14533, 13512, 54472, 86732, 33490, 93907, 88788, 29397, 38615, 22751, 45285, 29414, 65769, 62702, 78575, 88304, 83185, 91888, 25848, 20216, 34047, 37119, 86274, 17668, 61701, 64773, 26375, 83204, 87304, 30989, 92431, 83216, 25873, 82705, 65303, 69402, 14107, 17692, 35099, 99101, 96543, 18208, 86825, 62250, 55090, 68402, 44853, 61237, 24386, 99140, 90439, 82252, 78160, 31570, 32092, 11102, 94559, 77670, 55143, 63335, 45418, 45420, 47468, 96110, 50543, 26996, 38261, 49013, 80758, 77180, 82815, 18306, 40835, 30596, 35716, 45960, 55690, 64395, 79243, 65937, 53650, 60307, 91537, 10133, 19863, 27545, 96665, 15771, 16284, 33179, 78749, 93085, 96155, 19873, 56739, 84900, 36776, 30122, 59819, 17836, 86956, 52655, 34226, 46514, 48562, 54196, 57270, 60343, 77747, 92089, 17851, 67003, 66495, 16322, 95172, 19910, 31687, 55243, 98255, 83410, 63445, 28118, 40923, 96732, 18402, 21476, 39908, 44005, 63974, 35817, 68076, 43503, 50671, 26099, 20468, 14840, 13819, 33791]

In [136]:
final = set(attempts).symmetric_difference(grades)
final

{11102,
 23055,
 34285,
 40513,
 42798,
 45927,
 47580,
 47931,
 49753,
 50745,
 50907,
 51025,
 56194,
 57380,
 65229,
 66205,
 67736,
 68113,
 74969,
 79300,
 83832,
 86077,
 89018,
 99858}